execution:
    uuid: 44030b25-a90b-4f7e-ad35-4540bc0b16dc
    runtime:
        start: 2020-04-16T17:35:06.951484-07:00
        end: 2020-04-16T17:40:41.903687-07:00
        duration: 5 minutes, 34 seconds, and 952203 microseconds

action:
    type: method
    plugin: !ref 'environment:plugins:micom'
    action: db
    inputs: []
    parameters:
    -   meta: !metadata 'meta.tsv'
    -   rank: species
    -   threads: 16
    output-name: metabolic_models
    citations:
    - !cite 'action|micom:0.5.4|method:db|0'
    - !cite 'action|micom:0.5.4|method:db|1'
    - !cite 'action|micom:0.5.4|method:db|2'

transformers:
    output:
    -   from: JSONDirectory
        to: JSONDirectory

environment:
    platform: linux-x86_64
    python: |-
        3.6.10 | packaged by conda-forge | (default, Apr  6 2020, 14:52:36)
        [GCC 7.3.0]
    framework:
        version: 2020.5.0.dev0+5.g6a5739d
        website: https://qiime2.org
        citations:
        - !cite 'framework|qiime2:2020.5.0.dev0+5.g6a5739d|0'
    plugins:
        micom:
            version: 0.5.4
            website: https://github.com/micom-dev/q2-micom
    python-packages:
        zipp: 3.1.0
        xopen: 0.9.0
        widgetsnbextension: 3.5.1
        wheel: 0.34.2
        webencodings: 0.5.1
        wcwidth: 0.1.9
        urllib3: 1.25.8
        unifrac: 0.10.0
        umap-learn: 0.4.1
        tzlocal: 2.0.0
        typing-extensions: 3.7.4.1
        traitlets: 4.3.3
        tqdm: 4.45.0
        tornado: 6.0.4
        testpath: 0.4.4
        terminado: 0.8.3
        tbb: 2020.0.133
        tabulate: 0.8.7
        sympy: 1.5.1
        symengine: 0.6.1
        swiglpk: 4.65.0
        statsmodels: 0.11.1
        six: 1.14.0
        setuptools: 46.1.3.post20200325
        sepp: 4.3.10
        Send2Trash: 1.5.0
        seaborn: 0.10.0
        scipy: 1.4.1
        scikit-learn: 0.22.1
        scikit-bio: 0.5.5
        ruamel.yaml: 0.16.6
        ruamel.yaml.clib: 0.2.0
        requests: 2.23.0
        qiime2: 2020.5.0.dev0+5.g6a5739d
        q2templates: 2020.5.0.dev0
        q2cli: 2020.5.0.dev0+2.g7fb9228
        q2-vsearch: 2020.5.0.dev0+1.ge17a7d0
        q2-types: 2020.5.0.dev0+3.g004403d
        q2-taxa: 2020.5.0.dev0
        q2-sample-classifier: 2020.5.0.dev0
        q2-quality-filter: 2020.5.0.dev0
        q2-quality-control: 2020.5.0.dev0
        q2-phylogeny: 2020.5.0.dev0+3.g3e24893
        q2-micom: 0.5.4
        q2-metadata: 2020.5.0.dev0
        q2-longitudinal: 2020.5.0.dev0+1.g17f62e9
        q2-gneiss: 2020.5.0.dev0
        q2-fragment-insertion: 2020.5.0.dev0
        q2-feature-table: 2020.5.0.dev0+2.gc018f73
        q2-feature-classifier: 2020.5.0.dev0+2.gb2b4789
        q2-emperor: 2020.5.0.dev0
        q2-diversity: 2020.5.0.dev0+1.g67a6003
        q2-demux: 2020.5.0.dev0
        q2-deblur: 2020.5.0.dev0
        q2-dada2: 2020.5.0.dev0
        q2-cutadapt: 2020.5.0.dev0
        q2-composition: 2020.5.0.dev0+1.gae8045b
        q2-alignment: 2020.5.0.dev0+2.ge28754f
        pyzmq: 19.0.0
        PyYAML: 5.3.1
        pytz: '2019.3'
        python-libsbml: 5.18.0
        python-libsbml-experimental: 5.18.0
        python-dateutil: 2.8.1
        pytest: 5.4.1
        PySocks: 1.7.1
        pyrsistent: 0.16.0
        PyQtWebEngine: 5.12.1
        PyQt5: 5.12.3
        PyQt5-sip: 4.19.18
        pyparsing: 2.4.7
        pyOpenSSL: 19.1.0
        Pygments: 2.6.1
        pycparser: '2.20'
        pyarrow: 0.16.0
        py: 1.8.1
        ptyprocess: 0.6.0
        psutil: 5.7.0
        prompt-toolkit: 3.0.5
        prometheus-client: 0.7.1
        pluggy: 0.12.0
        pipdeptree: 0.13.2
        pip: 20.0.2
        Pillow: 7.1.1
        pickleshare: 0.7.5
        pexpect: 4.8.0
        patsy: 0.5.1
        parso: 0.7.0
        pandocfilters: 1.4.2
        pandas: 0.25.3
        packaging: '20.1'
        optlang: 1.4.4
        olefile: '0.46'
        numpy: 1.18.1
        numba: 0.48.0
        notebook: 6.0.3
        nose: 1.3.7
        networkx: '2.4'
        nbformat: 5.0.4
        nbconvert: 5.6.1
        natsort: 7.0.1
        msgpack: 1.0.0
        mpmath: 1.1.0
        more-itertools: 8.2.0
        mistune: 0.8.4
        micom: 0.11.2
        matplotlib: 3.2.1
        MarkupSafe: 1.1.1
        loky: 2.6.0
        loguru: 0.4.1
        lockfile: 0.12.2
        llvmlite: 0.31.0
        kiwisolver: 1.2.0
        jupyter-core: 4.6.3
        jupyter-client: 6.1.3
        jsonschema: 3.2.0
        joblib: 0.14.1
        Jinja2: 2.11.2
        jedi: 0.17.0
        ipywidgets: 7.5.1
        ipython: 7.13.0
        ipython-genutils: 0.2.0
        ipykernel: 5.2.0
        importlib-metadata: 1.6.0
        immutables: '0.11'
        ijson: '3.0'
        idna: '2.9'
        hdmedians: '0.13'
        h5py: 2.10.0
        gneiss: 0.4.6
        gmpy2: 2.1.0b1
        future: 0.18.2
        fastcluster: 1.1.26
        fastcache: 1.1.0
        entrypoints: '0.3'
        emperor: 1.0.0
        dnaio: 0.4.1
        depinfo: 1.5.3
        DendroPy: 4.4.0
        defusedxml: 0.6.0
        decorator: 4.4.2
        deblur: 1.1.0
        Cython: 0.29.16
        cycler: 0.10.0
        cutadapt: '2.9'
        cryptography: '2.8'
        contextvars: '2.4'
        cobra: 0.17.1
        cloudpickle: 1.3.0
        click: 7.1.1
        chardet: 3.0.4
        cffi: 1.14.0
        certifi: 2020.4.5.1
        CacheControl: 0.12.6
        bokeh: 2.0.1
        bleach: 3.1.4
        biom-format: 2.1.8
        bibtexparser: 1.1.0
        backcall: 0.1.0
        attrs: 19.3.0
        aiocontextvars: 0.2.2
